### ISSUE TITLE
Discussion: Support inline debt comments

### ISSUE THREAD

**Issue by Jeremie-Chauvel** [theodo/tyrion#101]
Hi,

I recently started using Tyrion to manage technical debt for my project and I was surprised to find out that inline comments are not supported.

example:
```typescript
let value: any // @debt quality:type
```
is not supported but the following is
```typescript
// @debt quality:type
let value: any
```
Is it a design choice ?

**Comment by MaximeThoonsen** [comment]
Hello @Jeremie-Chauvel , @Mondenx614. I made the change so it can work as you describe
