### ISSUE TITLE
Allow `// @best type(:subtype)* "{comment}"` to mark best practices

### ISSUE THREAD

**Issue by mikerid94** [theodo/tyrion#32]
Suggested CLI command:
`tyrion --best`

Suggested CLI print output:
```
Best Practices:
django:model:basic | {filename} - {line}
redux:action | {filename} - {line}
redux:reducer | {filename} - {line}
redux:saga:setup | {filename} - {line}
```

I think this would be really helpful in reducing the knowledge gaps between people on a team. 
The more experienced devs could leave `@best` tags around the codebase, and the less experienced devs could search for them before andoning or going with an incorrect tech strategy.

**Comment by MaximeThoonsen** [comment]
@mikerid94 @mattdean1 It's done =)
