### ISSUE TITLE
UX: after generating the report, Tyrion should display where to find it

### ISSUE THREAD

**Issue by MickaelBergem** [theodo/tyrion#43]
Today, you have to list the files in the folder to see the report name.

It would be nice to at least have the name of the report, or maybe the full path to the report.

![image](https://user-images.githubusercontent.com/3510190/59545324-9c1d8480-8ed1-11e9-8c61-26586351aa72.png)

**Comment by MaximeThoonsen** [comment]
Yes good idea !

**Comment by MaximeThoonsen** [comment]
@MickaelBergem should be good now :)
I added the fact that the report is automatically opened on a browser after being generated and an option to not open it as you are using it with your CI ;)
