### ISSUE TITLE
`tyrion -p . -e 60` no longer generates the html report

### ISSUE THREAD

**Issue by suixo-akido** [theodo/tyrion#59]
Running `tyrion -p . -e 60` used to generate the `tyrion_report.html` file. It just outputs the quality information now.

Let me know if you need more information :)

**Comment by MaximeThoonsen** [comment]
@suixo-akido @AleBlondin it seems the time has come to make some tests ... =)
I look at it

**Comment by MaximeThoonsen** [comment]
fixed
