### ISSUE TITLE
doesn't work with node 14.4

### ISSUE THREAD

**Issue by MaximeThoonsen** [theodo/tyrion#72]

**Comment by MaximeThoonsen** [comment]
We wait for the nodegit lib to be compatible with more recent version of node

**Comment by Sebdevar** [comment]
thanks for the info, will make sure to keep an eye on this issue ;)

**Comment by Sebdevar** [comment]
Actually, I just went over to their repo and it now seems to support node 14. You might wanna have a look into it :D

**Comment by MaximeThoonsen** [comment]
Hello @Sebdevar. Thanks for the ping, I have updated nodegit and now Tyrion is working with node 14 ;).
Are you using it on your project ?
